# Configuration Sentinelle Monitoring

# Base de données
DB_HOST="localhost"
DB_NAME="sentinelle"
DB_USER="sentinelle"
DB_PASSWORD="ChangeMoi"

# Répertoires
INSTALL_DIR="/opt/sentinelle"

LOG_DIR="/opt/sentinelle/logs"

SCRIPT_DIR="/opt/sentinelle/scripts"


# Seuils d'alertes

CPU_LIMIT=90
RAM_LIMIT=90
DISK_LIMIT=90


# Intervalle de surveillance en secondes

CHECK_INTERVAL=60


# Niveau de logs

LOG_LEVEL="INFO"
