FICHIER_JOURNAL="/var/log/auth.log"

MAX_TENTATIVES=5
FENETRE_TEMPS=600
DUREE_BAN=3600

BASE_BAN="/opt/sentinelle/ip_bannies.db"
LISTE_BLANCHE="/opt/sentinelle/liste_blanche.conf"
LOG="/opt/sentinelle/sentinelle.log"
